# Generated by Django 4.1.7 on 2023-08-02 08:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerceapp", "0002_contact"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="category",
            new_name="package_category",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_name",
            new_name="package_name",
        ),
        migrations.RemoveField(
            model_name="product",
            name="subcategory",
        ),
    ]
