# Generated by Django 4.1.7 on 2023-08-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerceapp", "0004_remove_product_package_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="package_category",
            field=models.CharField(default="", max_length=100),
        ),
    ]
