# Generated by Django 4.1.7 on 2023-08-02 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerceapp", "0006_rename_product_packages"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Packages",
            new_name="Package",
        ),
    ]
