# Generated by Django 4.1.7 on 2023-08-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerceapp", "0009_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name_plural": "Booked packages"},
        ),
        migrations.AddField(
            model_name="order",
            name="admission",
            field=models.BooleanField(default=False),
        ),
    ]
